semantic_layer:
  file_path: "assets/semantic_layer.txt"
  reload_interval: 3600

autogen:
  bi_analyst:
    model: "agentic-fbp-mini"  # Azure deployment name (update if different)
    temperature: 0.1
    max_tokens: 2000
    max_turns: 5
    agent_silent: false

data_platform:
  cube_categories:
    - finance

  default_search_limit: 50

  analysis_hints:
    - "Consider both measures and dimensions for complete financial analysis"
    - "Review cube relationships when combining multiple data sources"
    - "Use dimension variants (e.g., Account L1–L4) for drill-down and roll-up views"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "cube_analyst.log"

performance:
  cache_enabled: true
  cache_size: 1000
  timeout_seconds: 30
