semantic_layer:
  file_path: "assets/semantic_layer.txt"
  reload_interval: 3600

autogen:
  bi_analyst:
    model: "agentic-fbp-mini"  # Azure deployment name (update if different)
    temperature: 0.1
    max_tokens: 2000
    max_turns: 5
    agent_silent: false

data_platform:
  cube_categories:
    - finance

  default_search_limit: 50

analysis_hints:
    - "If the user mentions 'variance' or 'var', map it to the relevant VAR_* measure."
    - "If the user mentions 'SG&A' or 'sga', map it to SGandA_Expenses-related measures."
    - "If the user mentions 'net revenue' or 'sales', map it to Net_Revenue-related measures."
    - "If the user mentions 'operating profit' or 'EBIT', map it to Operating_Profit-related measures."
    - "Always include dimensions like Region, Function, Brand, or Period when the user specifies them."
    - "Convert periods like 'Q3 2025' or '2025 Q3' to the format '2025-Q3'."
    - "Focus on both measures and dimensions to ensure complete financial analysis."
    - "Use dimension variants (e.g., Account_L1–L4 or Parent_Function) for hierarchical drill-down or roll-up views."


logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "cube_analyst.log"

performance:
  cache_enabled: true
  cache_size: 1000
  timeout_seconds: 30
